#!/bin/bash
echo "OMNIBOT v2.5 - Quick Commands"
echo "=============================="
echo ""
echo "SETUP:"
echo "  ./install.sh                  - One-command install"
echo "  python src/main.py --setup    - Configure API keys"
echo ""
echo "TRADING:"
echo "  python src/main.py --mode cli - Start trading"
echo "  python src/main.py --trades   - View trades"
echo ""
echo "SERVICE:"
echo "  sudo systemctl start omnibot  - Start service"
echo "  sudo systemctl stop omnibot   - Stop service"
echo "  sudo journalctl -u omnibot -f - View logs"
echo ""
